### ISSUE TITLE
Feature - Separate containers for harvest (gather/consumer) and xloader

### ISSUE THREAD

**Issue by mjanez** [mjanez/ckan-docker#101]
## Info
To allow horizontal scalability, it would be better to use workers in separate containers rather than as background cron jobs within the `ckan' container. 

They communicate with the ckan container via redis, and need access to DB, solr and filesystem (config, storage, logs, etc.)

**References:**
* [ckanext-harvest production info](https://github.com/ckan/ckanext-harvest#setting-up-the-harvesters-on-a-production-server)
* https://github.com/ckan/ckan-docker/issues/118
* [`ckan-docker/Datapusher replacement`](https://github.com/ckan/ckan-docker/wiki/Replacing-DataPusher-with-XLoader)

## Example

```yaml
  gather_consumer:
    << : *default-common-ckan
    image: ${COMPOSE_PROJECT_NAME}-dcatapit_ckan:latest
    container_name: ${COMPOSE_PROJECT_NAME}-gather
    depends_on:
      ckan:
        condition: service_healthy
    entrypoint: /consumer-entrypoint.sh
    volumes:
      - ckan-data:/var/lib/ckan
      - ckan-config:/etc/ckan
      - ckan-logs:/var/log/ckan
      - ./docker/ckan/ckan_harvesting_gather.conf:/etc/supervisor/conf.d/ckan_harvesting.conf

  fetch_consumer:
    << : *default-common-ckan
    image: ${COMPOSE_PROJECT_NAME}-dcatapit_ckan:latest
    container_name: ${COMPOSE_PROJECT_NAME}-fetch
    depends_on:
      ckan:
        condition: service_healthy
    entrypoint: /consumer-entrypoint.sh
    volumes:
      - ckan-data:/var/lib/ckan
      - ckan-config:/etc/ckan
      - ckan-logs:/var/log/ckan
      - ./docker/ckan/ckan_harvesting_fetch.conf:/etc/supervisor/conf.d/ckan_harvesting.conf
```
